USE [$(DB_NAME)];
GO

GRANT CONNECT TO [$(APP_DB_USER)];

DENY ALTER ON SCHEMA::dbo TO [$(APP_DB_USER)];
REVOKE CONTROL ON SCHEMA::dbo FROM [$(APP_DB_USER)];
DENY CREATE TABLE TO [$(APP_DB_USER)];
DENY CREATE VIEW TO [$(APP_DB_USER)];
DENY CREATE PROCEDURE TO [$(APP_DB_USER)];
DENY CREATE FUNCTION TO [$(APP_DB_USER)];

GRANT SELECT ON dbo.VAITRO TO [$(APP_DB_USER)];
GRANT SELECT, INSERT, UPDATE ON dbo.TAIKHOAN TO [$(APP_DB_USER)];
GRANT SELECT, INSERT, UPDATE, DELETE ON dbo.REFRESH_TOKEN TO [$(APP_DB_USER)];
GRANT SELECT, INSERT ON dbo.AUDIT_LOG TO [$(APP_DB_USER)];
GRANT SELECT, INSERT, UPDATE ON dbo.APP_CONFIG TO [$(APP_DB_USER)];

GRANT SELECT, INSERT, UPDATE ON dbo.HANGTHANHVIEN TO [$(APP_DB_USER)];
GRANT SELECT, INSERT, UPDATE ON dbo.KHACHHANG TO [$(APP_DB_USER)];
GRANT SELECT, INSERT, UPDATE ON dbo.SANBAY TO [$(APP_DB_USER)];
GRANT SELECT, INSERT, UPDATE ON dbo.HANGVE TO [$(APP_DB_USER)];
GRANT SELECT, INSERT, UPDATE ON dbo.CHUYENBAY TO [$(APP_DB_USER)];
GRANT SELECT, INSERT, UPDATE ON dbo.TRUNGGIAN TO [$(APP_DB_USER)];
GRANT SELECT, INSERT, UPDATE ON dbo.CT_HANGVE TO [$(APP_DB_USER)];
GRANT SELECT, INSERT, UPDATE ON dbo.PHIEUDATCHO TO [$(APP_DB_USER)];
GRANT SELECT, INSERT, UPDATE ON dbo.VE TO [$(APP_DB_USER)];
GRANT SELECT, INSERT, UPDATE ON dbo.THANHTOAN TO [$(APP_DB_USER)];
GRANT SELECT, INSERT, UPDATE ON dbo.BANGGIA_HANHLY TO [$(APP_DB_USER)];
GRANT SELECT, INSERT, UPDATE ON dbo.GOIHANHLY TO [$(APP_DB_USER)];
GRANT SELECT, INSERT, UPDATE ON dbo.KIENHANHLY TO [$(APP_DB_USER)];
GRANT SELECT, INSERT, UPDATE ON dbo.CHECKIN TO [$(APP_DB_USER)];

GRANT EXECUTE ON SCHEMA::dbo TO [$(APP_DB_USER)];

DENY DELETE ON dbo.TAIKHOAN TO [$(APP_DB_USER)];
DENY DELETE ON dbo.AUDIT_LOG TO [$(APP_DB_USER)];
DENY DELETE ON dbo.APP_CONFIG TO [$(APP_DB_USER)];
DENY DELETE ON dbo.KHACHHANG TO [$(APP_DB_USER)];
DENY DELETE ON dbo.CHUYENBAY TO [$(APP_DB_USER)];
DENY DELETE ON dbo.VE TO [$(APP_DB_USER)];
GO
