USE [$(DB_NAME)];
GO

SET QUOTED_IDENTIFIER ON;
SET ANSI_NULLS ON;
GO

PRINT N'=== SEED: Payments (THANHTOAN) ===';
GO

-- ─── COMPLETED payments for HOP_LE tickets (linked to MaVe) ──────────────────

IF NOT EXISTS (SELECT 1 FROM dbo.THANHTOAN WHERE MaGiaoDich = 'SEED-TXN-001')
BEGIN
    DECLARE @V001 INT = (SELECT MaVe FROM dbo.VE WHERE MaVeCode = 'SEED-VE-001');
    INSERT INTO dbo.THANHTOAN (MaVe, SoTien, ThueVAT, PhuongThuc, TrangThaiThanhToan, MaGiaoDich, ThoiGianThanhToan)
    VALUES (@V001, 1200000, 120000, 'CREDIT_CARD', 'COMPLETED', 'SEED-TXN-001', DATEADD(HOUR, -48, SYSUTCDATETIME()));
END;
GO

IF NOT EXISTS (SELECT 1 FROM dbo.THANHTOAN WHERE MaGiaoDich = 'SEED-TXN-002')
BEGIN
    DECLARE @V002 INT = (SELECT MaVe FROM dbo.VE WHERE MaVeCode = 'SEED-VE-002');
    INSERT INTO dbo.THANHTOAN (MaVe, SoTien, ThueVAT, PhuongThuc, TrangThaiThanhToan, MaGiaoDich, ThoiGianThanhToan)
    VALUES (@V002, 1200000, 120000, 'BANK_TRANSFER', 'COMPLETED', 'SEED-TXN-002', DATEADD(HOUR, -48, SYSUTCDATETIME()));
END;
GO

IF NOT EXISTS (SELECT 1 FROM dbo.THANHTOAN WHERE MaGiaoDich = 'SEED-TXN-003')
BEGIN
    DECLARE @V003 INT = (SELECT MaVe FROM dbo.VE WHERE MaVeCode = 'SEED-VE-003');
    INSERT INTO dbo.THANHTOAN (MaVe, SoTien, ThueVAT, PhuongThuc, TrangThaiThanhToan, MaGiaoDich, ThoiGianThanhToan)
    VALUES (@V003, 3000000, 300000, 'CREDIT_CARD', 'COMPLETED', 'SEED-TXN-003', DATEADD(HOUR, -36, SYSUTCDATETIME()));
END;
GO

IF NOT EXISTS (SELECT 1 FROM dbo.THANHTOAN WHERE MaGiaoDich = 'SEED-TXN-004')
BEGIN
    DECLARE @V004 INT = (SELECT MaVe FROM dbo.VE WHERE MaVeCode = 'SEED-VE-004');
    INSERT INTO dbo.THANHTOAN (MaVe, SoTien, ThueVAT, PhuongThuc, TrangThaiThanhToan, MaGiaoDich, ThoiGianThanhToan)
    VALUES (@V004, 800000, 80000, 'E_WALLET', 'COMPLETED', 'SEED-TXN-004', DATEADD(HOUR, -24, SYSUTCDATETIME()));
END;
GO

IF NOT EXISTS (SELECT 1 FROM dbo.THANHTOAN WHERE MaGiaoDich = 'SEED-TXN-005')
BEGIN
    DECLARE @V005 INT = (SELECT MaVe FROM dbo.VE WHERE MaVeCode = 'SEED-VE-005');
    INSERT INTO dbo.THANHTOAN (MaVe, SoTien, ThueVAT, PhuongThuc, TrangThaiThanhToan, MaGiaoDich, ThoiGianThanhToan)
    VALUES (@V005, 800000, 80000, 'BANK_TRANSFER', 'COMPLETED', 'SEED-TXN-005', DATEADD(HOUR, -24, SYSUTCDATETIME()));
END;
GO

IF NOT EXISTS (SELECT 1 FROM dbo.THANHTOAN WHERE MaGiaoDich = 'SEED-TXN-006')
BEGIN
    DECLARE @V006 INT = (SELECT MaVe FROM dbo.VE WHERE MaVeCode = 'SEED-VE-006');
    INSERT INTO dbo.THANHTOAN (MaVe, SoTien, ThueVAT, PhuongThuc, TrangThaiThanhToan, MaGiaoDich, ThoiGianThanhToan)
    VALUES (@V006, 900000, 90000, 'MOMO', 'COMPLETED', 'SEED-TXN-006', DATEADD(HOUR, -20, SYSUTCDATETIME()));
END;
GO

IF NOT EXISTS (SELECT 1 FROM dbo.THANHTOAN WHERE MaGiaoDich = 'SEED-TXN-007')
BEGIN
    DECLARE @V007 INT = (SELECT MaVe FROM dbo.VE WHERE MaVeCode = 'SEED-VE-007');
    INSERT INTO dbo.THANHTOAN (MaVe, SoTien, ThueVAT, PhuongThuc, TrangThaiThanhToan, MaGiaoDich, ThoiGianThanhToan)
    VALUES (@V007, 2250000, 225000, 'CREDIT_CARD', 'COMPLETED', 'SEED-TXN-007', DATEADD(HOUR, -20, SYSUTCDATETIME()));
END;
GO

IF NOT EXISTS (SELECT 1 FROM dbo.THANHTOAN WHERE MaGiaoDich = 'SEED-TXN-008')
BEGIN
    DECLARE @V008 INT = (SELECT MaVe FROM dbo.VE WHERE MaVeCode = 'SEED-VE-008');
    INSERT INTO dbo.THANHTOAN (MaVe, SoTien, ThueVAT, PhuongThuc, TrangThaiThanhToan, MaGiaoDich, ThoiGianThanhToan)
    VALUES (@V008, 650000, 65000, 'E_WALLET', 'COMPLETED', 'SEED-TXN-008', DATEADD(HOUR, -72, SYSUTCDATETIME()));
END;
GO

IF NOT EXISTS (SELECT 1 FROM dbo.THANHTOAN WHERE MaGiaoDich = 'SEED-TXN-009')
BEGIN
    DECLARE @V009 INT = (SELECT MaVe FROM dbo.VE WHERE MaVeCode = 'SEED-VE-009');
    INSERT INTO dbo.THANHTOAN (MaVe, SoTien, ThueVAT, PhuongThuc, TrangThaiThanhToan, MaGiaoDich, ThoiGianThanhToan)
    VALUES (@V009, 1000000, 100000, 'BANK_TRANSFER', 'COMPLETED', 'SEED-TXN-009', DATEADD(HOUR, -72, SYSUTCDATETIME()));
END;
GO

IF NOT EXISTS (SELECT 1 FROM dbo.THANHTOAN WHERE MaGiaoDich = 'SEED-TXN-010')
BEGIN
    DECLARE @V010 INT = (SELECT MaVe FROM dbo.VE WHERE MaVeCode = 'SEED-VE-010');
    INSERT INTO dbo.THANHTOAN (MaVe, SoTien, ThueVAT, PhuongThuc, TrangThaiThanhToan, MaGiaoDich, ThoiGianThanhToan)
    VALUES (@V010, 1100000, 110000, 'CREDIT_CARD', 'COMPLETED', 'SEED-TXN-010', DATEADD(DAY, -5, SYSUTCDATETIME()));
END;
GO

IF NOT EXISTS (SELECT 1 FROM dbo.THANHTOAN WHERE MaGiaoDich = 'SEED-TXN-011')
BEGIN
    DECLARE @V011 INT = (SELECT MaVe FROM dbo.VE WHERE MaVeCode = 'SEED-VE-011');
    INSERT INTO dbo.THANHTOAN (MaVe, SoTien, ThueVAT, PhuongThuc, TrangThaiThanhToan, MaGiaoDich, ThoiGianThanhToan)
    VALUES (@V011, 1100000, 110000, 'MOMO', 'COMPLETED', 'SEED-TXN-011', DATEADD(DAY, -5, SYSUTCDATETIME()));
END;
GO

IF NOT EXISTS (SELECT 1 FROM dbo.THANHTOAN WHERE MaGiaoDich = 'SEED-TXN-012')
BEGIN
    DECLARE @V012 INT = (SELECT MaVe FROM dbo.VE WHERE MaVeCode = 'SEED-VE-012');
    INSERT INTO dbo.THANHTOAN (MaVe, SoTien, ThueVAT, PhuongThuc, TrangThaiThanhToan, MaGiaoDich, ThoiGianThanhToan)
    VALUES (@V012, 1875000, 187500, 'CREDIT_CARD', 'COMPLETED', 'SEED-TXN-012', DATEADD(DAY, -4, SYSUTCDATETIME()));
END;
GO

-- ─── PENDING payments for DANG_GIU_CHO (linked to MaPhieuDatCho) ─────────────

IF NOT EXISTS (SELECT 1 FROM dbo.THANHTOAN WHERE MaGiaoDich = 'SEED-TXN-013')
BEGIN
    DECLARE @PDC013 INT = (SELECT v.MaPhieuDatCho FROM dbo.VE v WHERE v.MaVeCode = 'SEED-VE-013');
    INSERT INTO dbo.THANHTOAN (MaPhieuDatCho, SoTien, ThueVAT, PhuongThuc, TrangThaiThanhToan, MaGiaoDich)
    VALUES (@PDC013, 750000, 75000, 'BANK_TRANSFER', 'PENDING', 'SEED-TXN-013');
END;
GO

IF NOT EXISTS (SELECT 1 FROM dbo.THANHTOAN WHERE MaGiaoDich = 'SEED-TXN-014')
BEGIN
    DECLARE @PDC014 INT = (SELECT v.MaPhieuDatCho FROM dbo.VE v WHERE v.MaVeCode = 'SEED-VE-014');
    INSERT INTO dbo.THANHTOAN (MaPhieuDatCho, SoTien, ThueVAT, PhuongThuc, TrangThaiThanhToan, MaGiaoDich)
    VALUES (@PDC014, 1050000, 105000, 'E_WALLET', 'PENDING', 'SEED-TXN-014');
END;
GO

IF NOT EXISTS (SELECT 1 FROM dbo.THANHTOAN WHERE MaGiaoDich = 'SEED-TXN-015')
BEGIN
    DECLARE @PDC015 INT = (SELECT v.MaPhieuDatCho FROM dbo.VE v WHERE v.MaVeCode = 'SEED-VE-015');
    INSERT INTO dbo.THANHTOAN (MaPhieuDatCho, SoTien, ThueVAT, PhuongThuc, TrangThaiThanhToan, MaGiaoDich)
    VALUES (@PDC015, 900000, 90000, 'CREDIT_CARD', 'PENDING', 'SEED-TXN-015');
END;
GO

IF NOT EXISTS (SELECT 1 FROM dbo.THANHTOAN WHERE MaGiaoDich = 'SEED-TXN-016')
BEGIN
    DECLARE @PDC016 INT = (SELECT v.MaPhieuDatCho FROM dbo.VE v WHERE v.MaVeCode = 'SEED-VE-016');
    INSERT INTO dbo.THANHTOAN (MaPhieuDatCho, SoTien, ThueVAT, PhuongThuc, TrangThaiThanhToan, MaGiaoDich)
    VALUES (@PDC016, 700000, 70000, 'MOMO', 'PENDING', 'SEED-TXN-016');
END;
GO

-- ─── COMPLETED payments for DA_HUY tickets ────────────────────────────────────

IF NOT EXISTS (SELECT 1 FROM dbo.THANHTOAN WHERE MaGiaoDich = 'SEED-TXN-017')
BEGIN
    DECLARE @V017 INT = (SELECT MaVe FROM dbo.VE WHERE MaVeCode = 'SEED-VE-017');
    INSERT INTO dbo.THANHTOAN (MaVe, SoTien, ThueVAT, PhuongThuc, TrangThaiThanhToan, MaGiaoDich, ThoiGianThanhToan)
    VALUES (@V017, 650000, 65000, 'CREDIT_CARD', 'COMPLETED', 'SEED-TXN-017', DATEADD(DAY, -2, SYSUTCDATETIME()));
END;
GO

IF NOT EXISTS (SELECT 1 FROM dbo.THANHTOAN WHERE MaGiaoDich = 'SEED-TXN-018')
BEGIN
    DECLARE @V018 INT = (SELECT MaVe FROM dbo.VE WHERE MaVeCode = 'SEED-VE-018');
    INSERT INTO dbo.THANHTOAN (MaVe, SoTien, ThueVAT, PhuongThuc, TrangThaiThanhToan, MaGiaoDich, ThoiGianThanhToan)
    VALUES (@V018, 1000000, 100000, 'BANK_TRANSFER', 'COMPLETED', 'SEED-TXN-018', DATEADD(DAY, -3, SYSUTCDATETIME()));
END;
GO

IF NOT EXISTS (SELECT 1 FROM dbo.THANHTOAN WHERE MaGiaoDich = 'SEED-TXN-019')
BEGIN
    DECLARE @V019 INT = (SELECT MaVe FROM dbo.VE WHERE MaVeCode = 'SEED-VE-019');
    INSERT INTO dbo.THANHTOAN (MaVe, SoTien, ThueVAT, PhuongThuc, TrangThaiThanhToan, MaGiaoDich, ThoiGianThanhToan)
    VALUES (@V019, 1200000, 120000, 'CREDIT_CARD', 'COMPLETED', 'SEED-TXN-019', DATEADD(DAY, -4, SYSUTCDATETIME()));
END;
GO

IF NOT EXISTS (SELECT 1 FROM dbo.THANHTOAN WHERE MaGiaoDich = 'SEED-TXN-020')
BEGIN
    DECLARE @V020 INT = (SELECT MaVe FROM dbo.VE WHERE MaVeCode = 'SEED-VE-020');
    INSERT INTO dbo.THANHTOAN (MaVe, SoTien, ThueVAT, PhuongThuc, TrangThaiThanhToan, MaGiaoDich, ThoiGianThanhToan)
    VALUES (@V020, 800000, 80000, 'BANK_TRANSFER', 'COMPLETED', 'SEED-TXN-020', DATEADD(DAY, -4, SYSUTCDATETIME()));
END;
GO

PRINT N'=== Payments seed completed ===';
GO
