USE [$(DB_NAME)];
GO

IF COL_LENGTH(N'dbo.THANHTOAN', N'LoaiThanhToan') IS NULL
BEGIN
    ALTER TABLE dbo.THANHTOAN
        ADD LoaiThanhToan VARCHAR(30) NOT NULL
            CONSTRAINT DF_THANHTOAN_LoaiThanhToan DEFAULT 'TICKET';
END;
GO

IF OBJECT_ID(N'dbo.CK_THANHTOAN_Loai', N'C') IS NULL
BEGIN
    ALTER TABLE dbo.THANHTOAN WITH CHECK
        ADD CONSTRAINT CK_THANHTOAN_Loai
            CHECK (LoaiThanhToan IN ('TICKET', 'BAGGAGE', 'UPGRADE', 'SERVICE'));
END;
GO
