USE [$(DB_NAME)];
GO

IF OBJECT_ID(N'dbo.VAITRO', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.VAITRO (
        MaVaiTro       INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_VAITRO PRIMARY KEY,
        TenVaiTro      NVARCHAR(50) NOT NULL CONSTRAINT UQ_VAITRO_TenVaiTro UNIQUE,
        MoTa           NVARCHAR(200) NULL,
        CreatedAt      DATETIME2(0) NOT NULL CONSTRAINT DF_VAITRO_CreatedAt DEFAULT SYSUTCDATETIME()
    );
END;
GO

IF OBJECT_ID(N'dbo.TAIKHOAN', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.TAIKHOAN (
        MaTaiKhoan     INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_TAIKHOAN PRIMARY KEY,
        TenDangNhap    VARCHAR(50) NOT NULL CONSTRAINT UQ_TAIKHOAN_TenDangNhap UNIQUE,
        MatKhauHash    VARCHAR(255) NOT NULL,
        MaVaiTro       INT NOT NULL,
        MaKhachHang    INT NULL,
        Email          VARCHAR(100) NULL,
        TrangThai      TINYINT NOT NULL CONSTRAINT DF_TAIKHOAN_TrangThai DEFAULT 1,
        CreatedAt      DATETIME2(0) NOT NULL CONSTRAINT DF_TAIKHOAN_CreatedAt DEFAULT SYSUTCDATETIME(),
        UpdatedAt      DATETIME2(0) NOT NULL CONSTRAINT DF_TAIKHOAN_UpdatedAt DEFAULT SYSUTCDATETIME(),
        LastLogin      DATETIME2(0) NULL,
        CONSTRAINT FK_TAIKHOAN_VAITRO FOREIGN KEY (MaVaiTro) REFERENCES dbo.VAITRO(MaVaiTro),
        CONSTRAINT CK_TAIKHOAN_TrangThai CHECK (TrangThai IN (0, 1))
    );
END;
GO

IF OBJECT_ID(N'dbo.REFRESH_TOKEN', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.REFRESH_TOKEN (
        Id             BIGINT IDENTITY(1,1) NOT NULL CONSTRAINT PK_REFRESH_TOKEN PRIMARY KEY,
        MaTaiKhoan     INT NOT NULL,
        TokenHash      VARCHAR(255) NOT NULL CONSTRAINT UQ_REFRESH_TOKEN_TokenHash UNIQUE,
        ExpiresAt      DATETIME2(0) NOT NULL,
        IsRevoked      BIT NOT NULL CONSTRAINT DF_REFRESH_TOKEN_IsRevoked DEFAULT 0,
        CreatedAt      DATETIME2(0) NOT NULL CONSTRAINT DF_REFRESH_TOKEN_CreatedAt DEFAULT SYSUTCDATETIME(),
        CONSTRAINT FK_REFRESH_TOKEN_TAIKHOAN FOREIGN KEY (MaTaiKhoan) REFERENCES dbo.TAIKHOAN(MaTaiKhoan)
    );
END;
GO

IF OBJECT_ID(N'dbo.AUDIT_LOG', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.AUDIT_LOG (
        Id             BIGINT IDENTITY(1,1) NOT NULL CONSTRAINT PK_AUDIT_LOG PRIMARY KEY,
        MaTaiKhoan     INT NULL,
        TenHanhDong    VARCHAR(100) NOT NULL,
        TenBang        VARCHAR(100) NULL,
        MaBanGhi       VARCHAR(50) NULL,
        DuLieuCu       NVARCHAR(MAX) NULL,
        DuLieuMoi      NVARCHAR(MAX) NULL,
        IpAddress      VARCHAR(50) NULL,
        UserAgent      VARCHAR(500) NULL,
        ThoiGian       DATETIME2(0) NOT NULL CONSTRAINT DF_AUDIT_LOG_ThoiGian DEFAULT SYSUTCDATETIME(),
        CONSTRAINT FK_AUDIT_LOG_TAIKHOAN FOREIGN KEY (MaTaiKhoan) REFERENCES dbo.TAIKHOAN(MaTaiKhoan)
    );
END;
GO

IF OBJECT_ID(N'dbo.APP_CONFIG', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.APP_CONFIG (
        ConfigKey      VARCHAR(100) NOT NULL CONSTRAINT PK_APP_CONFIG PRIMARY KEY,
        ConfigValue    NVARCHAR(500) NOT NULL,
        MoTa           NVARCHAR(200) NULL,
        UpdatedBy      INT NULL,
        UpdatedAt      DATETIME2(0) NOT NULL CONSTRAINT DF_APP_CONFIG_UpdatedAt DEFAULT SYSUTCDATETIME(),
        CONSTRAINT FK_APP_CONFIG_TAIKHOAN FOREIGN KEY (UpdatedBy) REFERENCES dbo.TAIKHOAN(MaTaiKhoan)
    );
END;
GO
