USE [$(DB_NAME)];
GO

IF OBJECT_ID(N'dbo.HANGTHANHVIEN', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.HANGTHANHVIEN (
        MaHangThanhVien INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_HANGTHANHVIEN PRIMARY KEY,
        TenHang         NVARCHAR(50) NOT NULL CONSTRAINT UQ_HANGTHANHVIEN_TenHang UNIQUE,
        DiemToiThieu    INT NOT NULL CONSTRAINT DF_HANGTHANHVIEN_DiemToiThieu DEFAULT 0,
        TyLeGiamGia     DECIMAL(5,2) NOT NULL CONSTRAINT DF_HANGTHANHVIEN_TyLeGiamGia DEFAULT 0,
        CreatedAt       DATETIME2(0) NOT NULL CONSTRAINT DF_HANGTHANHVIEN_CreatedAt DEFAULT SYSUTCDATETIME(),
        UpdatedAt       DATETIME2(0) NOT NULL CONSTRAINT DF_HANGTHANHVIEN_UpdatedAt DEFAULT SYSUTCDATETIME(),
        CONSTRAINT CK_HANGTHANHVIEN_DiemToiThieu CHECK (DiemToiThieu >= 0),
        CONSTRAINT CK_HANGTHANHVIEN_TyLeGiamGia CHECK (TyLeGiamGia >= 0 AND TyLeGiamGia <= 100)
    );
END;
GO

IF OBJECT_ID(N'dbo.KHACHHANG', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.KHACHHANG (
        MaKhachHang     INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_KHACHHANG PRIMARY KEY,
        HoTen           NVARCHAR(150) NOT NULL,
        CCCD             VARCHAR(20) NULL,
        Email            VARCHAR(100) NULL,
        SoDienThoai      VARCHAR(20) NULL,
        NgaySinh         DATE NULL,
        MaHangThanhVien  INT NULL,
        DiemTichLuy      INT NOT NULL CONSTRAINT DF_KHACHHANG_DiemTichLuy DEFAULT 0,
        IsDeleted        BIT NOT NULL CONSTRAINT DF_KHACHHANG_IsDeleted DEFAULT 0,
        CreatedAt        DATETIME2(0) NOT NULL CONSTRAINT DF_KHACHHANG_CreatedAt DEFAULT SYSUTCDATETIME(),
        UpdatedAt        DATETIME2(0) NOT NULL CONSTRAINT DF_KHACHHANG_UpdatedAt DEFAULT SYSUTCDATETIME(),
        CONSTRAINT FK_KHACHHANG_HANGTHANHVIEN FOREIGN KEY (MaHangThanhVien) REFERENCES dbo.HANGTHANHVIEN(MaHangThanhVien),
        CONSTRAINT CK_KHACHHANG_DiemTichLuy CHECK (DiemTichLuy >= 0)
    );
END;
GO

IF OBJECT_ID(N'dbo.SANBAY', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.SANBAY (
        MaSanBay         VARCHAR(10) NOT NULL CONSTRAINT PK_SANBAY PRIMARY KEY,
        TenSanBay        NVARCHAR(150) NOT NULL,
        ThanhPho         NVARCHAR(100) NOT NULL,
        QuocGia          NVARCHAR(100) NOT NULL,
        IsActive         BIT NOT NULL CONSTRAINT DF_SANBAY_IsActive DEFAULT 1,
        CreatedAt        DATETIME2(0) NOT NULL CONSTRAINT DF_SANBAY_CreatedAt DEFAULT SYSUTCDATETIME(),
        UpdatedAt        DATETIME2(0) NOT NULL CONSTRAINT DF_SANBAY_UpdatedAt DEFAULT SYSUTCDATETIME()
    );
END;
GO
