USE [$(DB_NAME)];
GO

IF OBJECT_ID(N'dbo.HANGVE', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.HANGVE (
        MaHangVe         INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_HANGVE PRIMARY KEY,
        TenHangVe        NVARCHAR(50) NOT NULL CONSTRAINT UQ_HANGVE_TenHangVe UNIQUE,
        HeSoGia          DECIMAL(8,2) NOT NULL CONSTRAINT DF_HANGVE_HeSoGia DEFAULT 1,
        MoTa             NVARCHAR(200) NULL,
        IsActive         BIT NOT NULL CONSTRAINT DF_HANGVE_IsActive DEFAULT 1,
        CONSTRAINT CK_HANGVE_HeSoGia CHECK (HeSoGia > 0)
    );
END;
GO

IF OBJECT_ID(N'dbo.CHUYENBAY', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.CHUYENBAY (
        MaChuyenBay      INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_CHUYENBAY PRIMARY KEY,
        MaChuyenBayCode  VARCHAR(20) NOT NULL CONSTRAINT UQ_CHUYENBAY_MaChuyenBayCode UNIQUE,
        SanBayDi         VARCHAR(10) NOT NULL,
        SanBayDen        VARCHAR(10) NOT NULL,
        NgayGioBay       DATETIME2(0) NOT NULL,
        ThoiGianBay      INT NOT NULL,
        GiaCoBan         DECIMAL(18,2) NOT NULL,
        TrangThaiChuyenBay VARCHAR(30) NOT NULL CONSTRAINT DF_CHUYENBAY_TrangThai DEFAULT 'SCHEDULED',
        IsDeleted        BIT NOT NULL CONSTRAINT DF_CHUYENBAY_IsDeleted DEFAULT 0,
        CreatedAt        DATETIME2(0) NOT NULL CONSTRAINT DF_CHUYENBAY_CreatedAt DEFAULT SYSUTCDATETIME(),
        UpdatedAt        DATETIME2(0) NOT NULL CONSTRAINT DF_CHUYENBAY_UpdatedAt DEFAULT SYSUTCDATETIME(),
        CONSTRAINT FK_CHUYENBAY_SANBAY_DI FOREIGN KEY (SanBayDi) REFERENCES dbo.SANBAY(MaSanBay),
        CONSTRAINT FK_CHUYENBAY_SANBAY_DEN FOREIGN KEY (SanBayDen) REFERENCES dbo.SANBAY(MaSanBay),
        CONSTRAINT CK_CHUYENBAY_SanBay CHECK (SanBayDi <> SanBayDen),
        CONSTRAINT CK_CHUYENBAY_ThoiGian CHECK (ThoiGianBay >= 30),
        CONSTRAINT CK_CHUYENBAY_GiaCoBan CHECK (GiaCoBan >= 0)
    );
END;
GO

IF OBJECT_ID(N'dbo.TRUNGGIAN', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.TRUNGGIAN (
        MaTrungGian      INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_TRUNGGIAN PRIMARY KEY,
        MaChuyenBay      INT NOT NULL,
        MaSanBay         VARCHAR(10) NOT NULL,
        ThuTu            INT NOT NULL,
        ThoiGianDung     INT NOT NULL CONSTRAINT DF_TRUNGGIAN_ThoiGianDung DEFAULT 0,
        GhiChu           NVARCHAR(200) NULL,
        CONSTRAINT FK_TRUNGGIAN_CHUYENBAY FOREIGN KEY (MaChuyenBay) REFERENCES dbo.CHUYENBAY(MaChuyenBay),
        CONSTRAINT FK_TRUNGGIAN_SANBAY FOREIGN KEY (MaSanBay) REFERENCES dbo.SANBAY(MaSanBay),
        CONSTRAINT UQ_TRUNGGIAN_ChuyenBayThuTu UNIQUE (MaChuyenBay, ThuTu),
        CONSTRAINT CK_TRUNGGIAN_ThuTu CHECK (ThuTu > 0),
        CONSTRAINT CK_TRUNGGIAN_ThoiGianDung CHECK (ThoiGianDung >= 0)
    );
END;
GO

IF OBJECT_ID(N'dbo.CT_HANGVE', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.CT_HANGVE (
        MaChuyenBay      INT NOT NULL,
        MaHangVe         INT NOT NULL,
        SoLuong          INT NOT NULL,
        SoGheDaDat       INT NOT NULL CONSTRAINT DF_CT_HANGVE_SoGheDaDat DEFAULT 0,
        DonGia           DECIMAL(18,2) NOT NULL,
        CONSTRAINT PK_CT_HANGVE PRIMARY KEY (MaChuyenBay, MaHangVe),
        CONSTRAINT FK_CT_HANGVE_CHUYENBAY FOREIGN KEY (MaChuyenBay) REFERENCES dbo.CHUYENBAY(MaChuyenBay),
        CONSTRAINT FK_CT_HANGVE_HANGVE FOREIGN KEY (MaHangVe) REFERENCES dbo.HANGVE(MaHangVe),
        CONSTRAINT CK_CTHANGVE_SoLuong CHECK (SoLuong >= 0 AND SoGheDaDat >= 0 AND SoGheDaDat <= SoLuong),
        CONSTRAINT CK_CT_HANGVE_DonGia CHECK (DonGia >= 0)
    );
END;
GO
