USE [$(DB_NAME)];
GO

IF OBJECT_ID(N'dbo.PHIEUDATCHO', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.PHIEUDATCHO (
        MaPhieuDatCho    INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_PHIEUDATCHO PRIMARY KEY,
        MaKhachHang      INT NOT NULL,
        MaChuyenBay      INT NOT NULL,
        MaHangVe         INT NOT NULL,
        SoLuongVe        INT NOT NULL CONSTRAINT DF_PHIEUDATCHO_SoLuongVe DEFAULT 1,
        TongTien         DECIMAL(18,2) NOT NULL,
        TrangThaiDatCho  VARCHAR(30) NOT NULL CONSTRAINT DF_PHIEUDATCHO_TrangThai DEFAULT 'PENDING',
        HanThanhToan     DATETIME2(0) NOT NULL,
        CreatedAt        DATETIME2(0) NOT NULL CONSTRAINT DF_PHIEUDATCHO_CreatedAt DEFAULT SYSUTCDATETIME(),
        UpdatedAt        DATETIME2(0) NOT NULL CONSTRAINT DF_PHIEUDATCHO_UpdatedAt DEFAULT SYSUTCDATETIME(),
        CONSTRAINT FK_PHIEUDATCHO_KHACHHANG FOREIGN KEY (MaKhachHang) REFERENCES dbo.KHACHHANG(MaKhachHang),
        CONSTRAINT FK_PHIEUDATCHO_CHUYENBAY FOREIGN KEY (MaChuyenBay) REFERENCES dbo.CHUYENBAY(MaChuyenBay),
        CONSTRAINT FK_PHIEUDATCHO_HANGVE FOREIGN KEY (MaHangVe) REFERENCES dbo.HANGVE(MaHangVe),
        CONSTRAINT CK_PHIEUDATCHO_SoLuongVe CHECK (SoLuongVe > 0),
        CONSTRAINT CK_PHIEUDATCHO_TongTien CHECK (TongTien >= 0)
    );
END;
GO

IF OBJECT_ID(N'dbo.VE', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.VE (
        MaVe             INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_VE PRIMARY KEY,
        MaVeCode         VARCHAR(30) NOT NULL CONSTRAINT UQ_VE_MaVeCode UNIQUE,
        MaChuyenBay      INT NOT NULL,
        MaHangVe         INT NOT NULL,
        MaKhachHang      INT NOT NULL,
        MaPhieuDatCho    INT NULL,
        GiaVe            DECIMAL(18,2) NOT NULL,
        TrangThaiVe      VARCHAR(30) NOT NULL CONSTRAINT DF_VE_TrangThai DEFAULT 'ISSUED',
        IsDeleted        BIT NOT NULL CONSTRAINT DF_VE_IsDeleted DEFAULT 0,
        CreatedAt        DATETIME2(0) NOT NULL CONSTRAINT DF_VE_CreatedAt DEFAULT SYSUTCDATETIME(),
        UpdatedAt        DATETIME2(0) NOT NULL CONSTRAINT DF_VE_UpdatedAt DEFAULT SYSUTCDATETIME(),
        CONSTRAINT FK_VE_CHUYENBAY FOREIGN KEY (MaChuyenBay) REFERENCES dbo.CHUYENBAY(MaChuyenBay),
        CONSTRAINT FK_VE_HANGVE FOREIGN KEY (MaHangVe) REFERENCES dbo.HANGVE(MaHangVe),
        CONSTRAINT FK_VE_KHACHHANG FOREIGN KEY (MaKhachHang) REFERENCES dbo.KHACHHANG(MaKhachHang),
        CONSTRAINT FK_VE_PHIEUDATCHO FOREIGN KEY (MaPhieuDatCho) REFERENCES dbo.PHIEUDATCHO(MaPhieuDatCho),
        CONSTRAINT CK_VE_GiaVe CHECK (GiaVe >= 0)
    );
END;
GO
