USE [$(DB_NAME)];
GO

IF OBJECT_ID(N'dbo.THANHTOAN', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.THANHTOAN (
        MaThanhToan      INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_THANHTOAN PRIMARY KEY,
        MaVe             INT NULL,
        MaPhieuDatCho    INT NULL,
        LoaiThanhToan    VARCHAR(30) NOT NULL CONSTRAINT DF_THANHTOAN_LoaiThanhToan DEFAULT 'TICKET',
        SoTien           DECIMAL(18,2) NOT NULL,
        ThueVAT          DECIMAL(18,2) NOT NULL CONSTRAINT DF_THANHTOAN_ThueVAT DEFAULT 0,
        PhuongThuc       VARCHAR(30) NOT NULL,
        TrangThaiThanhToan VARCHAR(30) NOT NULL CONSTRAINT DF_THANHTOAN_TrangThai DEFAULT 'PENDING',
        MaGiaoDich       VARCHAR(100) NULL,
        ThoiGianThanhToan DATETIME2(0) NULL,
        CreatedAt        DATETIME2(0) NOT NULL CONSTRAINT DF_THANHTOAN_CreatedAt DEFAULT SYSUTCDATETIME(),
        UpdatedAt        DATETIME2(0) NOT NULL CONSTRAINT DF_THANHTOAN_UpdatedAt DEFAULT SYSUTCDATETIME(),
        CONSTRAINT FK_THANHTOAN_VE FOREIGN KEY (MaVe) REFERENCES dbo.VE(MaVe),
        CONSTRAINT FK_THANHTOAN_PHIEUDATCHO FOREIGN KEY (MaPhieuDatCho) REFERENCES dbo.PHIEUDATCHO(MaPhieuDatCho),
        CONSTRAINT CK_THANHTOAN_DoiTuong CHECK (MaVe IS NOT NULL OR MaPhieuDatCho IS NOT NULL),
        CONSTRAINT CK_THANHTOAN_Loai CHECK (LoaiThanhToan IN ('TICKET', 'BAGGAGE', 'UPGRADE', 'SERVICE')),
        CONSTRAINT CK_THANHTOAN_SoTien CHECK (SoTien >= 0 AND ThueVAT >= 0)
    );
END;
GO
