USE [$(DB_NAME)];
GO

IF OBJECT_ID(N'dbo.BANGGIA_HANHLY', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.BANGGIA_HANHLY (
        MaBangGia        INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_BANGGIA_HANHLY PRIMARY KEY,
        TenGoi           NVARCHAR(100) NOT NULL,
        TrongLuongToiDa  DECIMAL(6,2) NOT NULL,
        GiaMuaTruoc      DECIMAL(18,2) NOT NULL,
        GiaTaiSanBay     DECIMAL(18,2) NOT NULL,
        IsActive         BIT NOT NULL CONSTRAINT DF_BANGGIA_HANHLY_IsActive DEFAULT 1,
        CreatedAt        DATETIME2(0) NOT NULL CONSTRAINT DF_BANGGIA_HANHLY_CreatedAt DEFAULT SYSUTCDATETIME(),
        UpdatedAt        DATETIME2(0) NOT NULL CONSTRAINT DF_BANGGIA_HANHLY_UpdatedAt DEFAULT SYSUTCDATETIME(),
        CONSTRAINT CK_BANGGIA_HANHLY_TrongLuong CHECK (TrongLuongToiDa > 0),
        CONSTRAINT CK_BANGGIA_HANHLY_Gia CHECK (GiaMuaTruoc >= 0 AND GiaTaiSanBay >= 0)
    );
END;
GO

IF OBJECT_ID(N'dbo.GOIHANHLY', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.GOIHANHLY (
        MaGoiHanhLy      INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_GOIHANHLY PRIMARY KEY,
        MaVe             INT NOT NULL,
        MaBangGia        INT NOT NULL,
        TongTrongLuong   DECIMAL(6,2) NOT NULL CONSTRAINT DF_GOIHANHLY_TongTrongLuong DEFAULT 0,
        TongPhi          DECIMAL(18,2) NOT NULL CONSTRAINT DF_GOIHANHLY_TongPhi DEFAULT 0,
        TrangThai        VARCHAR(30) NOT NULL CONSTRAINT DF_GOIHANHLY_TrangThai DEFAULT 'REGISTERED',
        CreatedAt        DATETIME2(0) NOT NULL CONSTRAINT DF_GOIHANHLY_CreatedAt DEFAULT SYSUTCDATETIME(),
        UpdatedAt        DATETIME2(0) NOT NULL CONSTRAINT DF_GOIHANHLY_UpdatedAt DEFAULT SYSUTCDATETIME(),
        CONSTRAINT FK_GOIHANHLY_VE FOREIGN KEY (MaVe) REFERENCES dbo.VE(MaVe),
        CONSTRAINT FK_GOIHANHLY_BANGGIA FOREIGN KEY (MaBangGia) REFERENCES dbo.BANGGIA_HANHLY(MaBangGia),
        CONSTRAINT CK_GOIHANHLY_TrongLuong CHECK (TongTrongLuong >= 0),
        CONSTRAINT CK_GOIHANHLY_TongPhi CHECK (TongPhi >= 0)
    );
END;
GO

IF OBJECT_ID(N'dbo.KIENHANHLY', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.KIENHANHLY (
        MaKienHanhLy     INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_KIENHANHLY PRIMARY KEY,
        MaGoiHanhLy      INT NOT NULL,
        MaTheHanhLy      VARCHAR(50) NOT NULL CONSTRAINT UQ_KIENHANHLY_MaTheHanhLy UNIQUE,
        TrongLuong       DECIMAL(6,2) NOT NULL,
        GhiChu           NVARCHAR(200) NULL,
        CreatedAt        DATETIME2(0) NOT NULL CONSTRAINT DF_KIENHANHLY_CreatedAt DEFAULT SYSUTCDATETIME(),
        CONSTRAINT FK_KIENHANHLY_GOIHANHLY FOREIGN KEY (MaGoiHanhLy) REFERENCES dbo.GOIHANHLY(MaGoiHanhLy),
        CONSTRAINT CK_KIEN_TrongLuong CHECK (TrongLuong > 0 AND TrongLuong <= 32)
    );
END;
GO
