USE [$(DB_NAME)];
GO

IF OBJECT_ID(N'dbo.CHECKIN', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.CHECKIN (
        MaCheckIn        INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_CHECKIN PRIMARY KEY,
        MaVe             INT NOT NULL CONSTRAINT UQ_CHECKIN_MaVe UNIQUE,
        SoGhe            VARCHAR(10) NOT NULL,
        BoardingPassCode VARCHAR(100) NOT NULL CONSTRAINT UQ_CHECKIN_BoardingPassCode UNIQUE,
        CheckInAt        DATETIME2(0) NOT NULL CONSTRAINT DF_CHECKIN_CheckInAt DEFAULT SYSUTCDATETIME(),
        TrangThai        VARCHAR(30) NOT NULL CONSTRAINT DF_CHECKIN_TrangThai DEFAULT 'CHECKED_IN',
        CreatedAt        DATETIME2(0) NOT NULL CONSTRAINT DF_CHECKIN_CreatedAt DEFAULT SYSUTCDATETIME(),
        CONSTRAINT FK_CHECKIN_VE FOREIGN KEY (MaVe) REFERENCES dbo.VE(MaVe)
    );
END;
GO
