USE [$(DB_NAME)];
GO

SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
GO

IF NOT EXISTS (
    SELECT 1
    FROM sys.foreign_keys
    WHERE name = N'FK_TAIKHOAN_KHACHHANG'
)
BEGIN
    ALTER TABLE dbo.TAIKHOAN
        ADD CONSTRAINT FK_TAIKHOAN_KHACHHANG
        FOREIGN KEY (MaKhachHang) REFERENCES dbo.KHACHHANG(MaKhachHang);
END;
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_TAIKHOAN_MaVaiTro' AND object_id = OBJECT_ID(N'dbo.TAIKHOAN'))
    CREATE INDEX IX_TAIKHOAN_MaVaiTro ON dbo.TAIKHOAN(MaVaiTro);
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_TAIKHOAN_MaKhachHang' AND object_id = OBJECT_ID(N'dbo.TAIKHOAN'))
    CREATE INDEX IX_TAIKHOAN_MaKhachHang ON dbo.TAIKHOAN(MaKhachHang);
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_REFRESH_TOKEN_MaTaiKhoan' AND object_id = OBJECT_ID(N'dbo.REFRESH_TOKEN'))
    CREATE INDEX IX_REFRESH_TOKEN_MaTaiKhoan ON dbo.REFRESH_TOKEN(MaTaiKhoan);
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_AUDIT_LOG_MaTaiKhoan' AND object_id = OBJECT_ID(N'dbo.AUDIT_LOG'))
    CREATE INDEX IX_AUDIT_LOG_MaTaiKhoan ON dbo.AUDIT_LOG(MaTaiKhoan);
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_THAM_SO_CapNhatBoi' AND object_id = OBJECT_ID(N'dbo.THAM_SO'))
    CREATE INDEX IX_THAM_SO_CapNhatBoi ON dbo.THAM_SO(CapNhatBoi);
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_KHACHHANG_MaHangThanhVien' AND object_id = OBJECT_ID(N'dbo.KHACHHANG'))
    CREATE INDEX IX_KHACHHANG_MaHangThanhVien ON dbo.KHACHHANG(MaHangThanhVien);
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'UX_KHACHHANG_CCCD' AND object_id = OBJECT_ID(N'dbo.KHACHHANG'))
    CREATE UNIQUE INDEX UX_KHACHHANG_CCCD ON dbo.KHACHHANG(CCCD) WHERE CCCD IS NOT NULL;
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_CHUYENBAY_SanBayDi' AND object_id = OBJECT_ID(N'dbo.CHUYENBAY'))
    CREATE INDEX IX_CHUYENBAY_SanBayDi ON dbo.CHUYENBAY(SanBayDi);
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_CHUYENBAY_SanBayDen' AND object_id = OBJECT_ID(N'dbo.CHUYENBAY'))
    CREATE INDEX IX_CHUYENBAY_SanBayDen ON dbo.CHUYENBAY(SanBayDen);
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_CHUYENBAY_NgayGioBay' AND object_id = OBJECT_ID(N'dbo.CHUYENBAY'))
    CREATE INDEX IX_CHUYENBAY_NgayGioBay ON dbo.CHUYENBAY(NgayGioBay);
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_TRUNGGIAN_MaSanBay' AND object_id = OBJECT_ID(N'dbo.TRUNGGIAN'))
    CREATE INDEX IX_TRUNGGIAN_MaSanBay ON dbo.TRUNGGIAN(MaSanBay);
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_CT_HANGVE_MaHangVe' AND object_id = OBJECT_ID(N'dbo.CT_HANGVE'))
    CREATE INDEX IX_CT_HANGVE_MaHangVe ON dbo.CT_HANGVE(MaHangVe);
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_PHIEUDATCHO_MaKhachHang' AND object_id = OBJECT_ID(N'dbo.PHIEUDATCHO'))
    CREATE INDEX IX_PHIEUDATCHO_MaKhachHang ON dbo.PHIEUDATCHO(MaKhachHang);
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_PHIEUDATCHO_MaChuyenBay' AND object_id = OBJECT_ID(N'dbo.PHIEUDATCHO'))
    CREATE INDEX IX_PHIEUDATCHO_MaChuyenBay ON dbo.PHIEUDATCHO(MaChuyenBay);
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_PHIEUDATCHO_MaHangVe' AND object_id = OBJECT_ID(N'dbo.PHIEUDATCHO'))
    CREATE INDEX IX_PHIEUDATCHO_MaHangVe ON dbo.PHIEUDATCHO(MaHangVe);
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_VE_MaChuyenBay' AND object_id = OBJECT_ID(N'dbo.VE'))
    CREATE INDEX IX_VE_MaChuyenBay ON dbo.VE(MaChuyenBay);
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_VE_MaHangVe' AND object_id = OBJECT_ID(N'dbo.VE'))
    CREATE INDEX IX_VE_MaHangVe ON dbo.VE(MaHangVe);
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_VE_MaKhachHang' AND object_id = OBJECT_ID(N'dbo.VE'))
    CREATE INDEX IX_VE_MaKhachHang ON dbo.VE(MaKhachHang);
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_VE_MaPhieuDatCho' AND object_id = OBJECT_ID(N'dbo.VE'))
    CREATE INDEX IX_VE_MaPhieuDatCho ON dbo.VE(MaPhieuDatCho);
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_VE_TrangThaiVe' AND object_id = OBJECT_ID(N'dbo.VE'))
    CREATE INDEX IX_VE_TrangThaiVe ON dbo.VE(TrangThaiVe);
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_THANHTOAN_MaVe' AND object_id = OBJECT_ID(N'dbo.THANHTOAN'))
    CREATE INDEX IX_THANHTOAN_MaVe ON dbo.THANHTOAN(MaVe);
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_THANHTOAN_MaPhieuDatCho' AND object_id = OBJECT_ID(N'dbo.THANHTOAN'))
    CREATE INDEX IX_THANHTOAN_MaPhieuDatCho ON dbo.THANHTOAN(MaPhieuDatCho);
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_GOIHANHLY_MaVe' AND object_id = OBJECT_ID(N'dbo.GOIHANHLY'))
    CREATE INDEX IX_GOIHANHLY_MaVe ON dbo.GOIHANHLY(MaVe);
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_GOIHANHLY_MaBangGia' AND object_id = OBJECT_ID(N'dbo.GOIHANHLY'))
    CREATE INDEX IX_GOIHANHLY_MaBangGia ON dbo.GOIHANHLY(MaBangGia);
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = N'IX_KIENHANHLY_MaGoiHanhLy' AND object_id = OBJECT_ID(N'dbo.KIENHANHLY'))
    CREATE INDEX IX_KIENHANHLY_MaGoiHanhLy ON dbo.KIENHANHLY(MaGoiHanhLy);
GO
